version: "3"
services:
  flask:
    ports:
      - 5000:5000
    #開発環境用環境変数を読み込む = このコンテナ自体の環境変数となる
    env_file: "prodenv.env"
    #開発用のgunicorn起動コマンド
    command: gunicorn -w 2 -b 0.0.0.0:5000 'apps.app:create_app("product")'
  nginx:
    #本番用のnginx設定ファイルのバインド
    volumes:
      - type: bind
        source: "./vue/my-vite-todo/dist"
        target: "/usr/share/nginx/html"
      - type: bind
        source: "./nginx/etc/nginx/prod_conf.d"
        target: "/etc/nginx/conf.d"
      - type: bind
        source: "/etc/letsencrypt/live/www.roosmemosite.net/fullchain.pem"
        target: "/etc/nginx/certs/server.crt"
      - type: bind
        source: "/etc/letsencrypt/live/www.roosmemosite.net/privkey.pem"
        target: "/etc/nginx/certs/server.key"
    ports:
      - 80:80
      - 443:443
# #サービス外ボリュームを作成(開発環境でのデータ永続化処理)
# volumes:
#   myvitetodo_db_datavol: